import '../styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 min-h-screen">
        {children}
      </body>
    </html>
  )
}
